/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contactbook;

import contactbook.EmailEntry.Format;
import contactbook.EmailEntry.InvalidEmailException;
import contactbook.Model.MissingNameException;
import contactbook.Model.NameDuplicateException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.JFrame;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 *
 * @author vlad
 */
public class EditEntryFrame extends javax.swing.JDialog {

    /**
     * Creates new form EditEntryFrame
     */	        
    
    private Model model;
    private CustomListModel emailsListModel;
    private Format curFormat = Format.HTML;
    
    
    
    private void fillContactData(ContactEntry contact) {
        System.out.println("Fillng data");
        nameTextField.setText(contact.getFirstName());
        lastNameTextField.setText(contact.getLastName());
        nicknameTextField.setText(contact.getNickname());
        titleTextField.setText(contact.getTitle());
    }
    
    public EditEntryFrame(JFrame parent, Model model) {
        super(parent);
        initComponents();
        if (model.getContactEntry() != null)
            fillContactData(model.getContactEntry());   
        this.model = model;
        emailsListModel = new CustomListModel(model.getEmailEntries());
        
        jList1.setModel(emailsListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeAddressDialog = new javax.swing.JDialog();
        changeAddressLabel = new javax.swing.JLabel();
        changeAddressTextField = new javax.swing.JTextField();
        changeConfirmButton = new javax.swing.JButton();
        changeCancelButton = new javax.swing.JButton();
        changeAddressErrorMessageLabel = new javax.swing.JLabel();
        formatButtonGroup = new javax.swing.ButtonGroup();
        NamePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        nicknameLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        nicknameTextField = new javax.swing.JTextField();
        errorMessageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        emailErrorMessageLabel = new javax.swing.JLabel();
        htmlRadioButton = new javax.swing.JRadioButton();
        plainTextRadioButton = new javax.swing.JRadioButton();
        customRadioButton = new javax.swing.JRadioButton();
        formatLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        changeAddressDialog.setResizable(false);

        changeAddressLabel.setText("Enter new address:");

        changeConfirmButton.setText("OK");
        changeConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeConfirmButtonActionPerformed(evt);
            }
        });

        changeCancelButton.setText("Cancel");
        changeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCancelButtonActionPerformed(evt);
            }
        });

        changeAddressErrorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout changeAddressDialogLayout = new javax.swing.GroupLayout(changeAddressDialog.getContentPane());
        changeAddressDialog.getContentPane().setLayout(changeAddressDialogLayout);
        changeAddressDialogLayout.setHorizontalGroup(
            changeAddressDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeAddressDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeConfirmButton)
                .addGap(71, 71, 71)
                .addComponent(changeCancelButton)
                .addGap(77, 77, 77))
            .addGroup(changeAddressDialogLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(changeAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changeAddressDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeAddressErrorMessageLabel)
                    .addComponent(changeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        changeAddressDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {changeCancelButton, changeConfirmButton});

        changeAddressDialogLayout.setVerticalGroup(
            changeAddressDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeAddressDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(changeAddressDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeAddressLabel)
                    .addComponent(changeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(changeAddressErrorMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changeAddressDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeConfirmButton)
                    .addComponent(changeCancelButton))
                .addContainerGap())
        );

        setTitle("Edit Entry");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        NamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        NamePanel.setToolTipText("Name");

        nameLabel.setText("Name:");

        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyTyped(evt);
            }
        });

        titleLabel.setText("Title:");

        lastNameLabel.setText("Last name:");

        nicknameLabel.setText("Nickname:");

        lastNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameTextFieldKeyTyped(evt);
            }
        });

        errorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout NamePanelLayout = new javax.swing.GroupLayout(NamePanel);
        NamePanel.setLayout(NamePanelLayout);
        NamePanelLayout.setHorizontalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorMessageLabel)
                    .addGroup(NamePanelLayout.createSequentialGroup()
                        .addGroup(NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NamePanelLayout.createSequentialGroup()
                                .addComponent(titleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NamePanelLayout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118)
                        .addGroup(NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(NamePanelLayout.createSequentialGroup()
                                .addComponent(nicknameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nicknameTextField))
                            .addGroup(NamePanelLayout.createSequentialGroup()
                                .addComponent(lastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))))
                .addGap(263, 263, 263))
        );

        NamePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lastNameTextField, nameTextField, nicknameTextField, titleTextField});

        NamePanelLayout.setVerticalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(nicknameLabel)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicknameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(errorMessageLabel)
                .addContainerGap())
        );

        NamePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lastNameLabel, lastNameTextField, nameLabel, nameTextField, nicknameLabel, nicknameTextField, titleLabel, titleTextField});

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        emailLabel.setText("E-mail address:");

        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
        });
        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyTyped(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "12", "123", "12" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        emailErrorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));

        formatButtonGroup.add(htmlRadioButton);
        htmlRadioButton.setSelected(true);
        htmlRadioButton.setText("HTML");
        htmlRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htmlRadioButtonActionPerformed(evt);
            }
        });

        formatButtonGroup.add(plainTextRadioButton);
        plainTextRadioButton.setText("Plain Text");
        plainTextRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainTextRadioButtonActionPerformed(evt);
            }
        });

        formatButtonGroup.add(customRadioButton);
        customRadioButton.setText("Custom");
        customRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customRadioButtonActionPerformed(evt);
            }
        });

        formatLabel.setText("Format:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(emailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeButton)
                            .addComponent(editButton)
                            .addComponent(addButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailErrorMessageLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(formatLabel)
                                .addGap(3, 3, 3)
                                .addComponent(htmlRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plainTextRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customRadioButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addButton, editButton, removeButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailErrorMessageLabel)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(htmlRadioButton)
                    .addComponent(plainTextRadioButton)
                    .addComponent(customRadioButton)
                    .addComponent(formatLabel)))
        );

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String email = emailTextField.getText();
        try {
            emailsListModel.add(new EmailEntry(email, curFormat));
            emailTextField.setText("");
        } catch (InvalidEmailException e) {
            emailErrorMessageLabel.setText("Please enter a correct e-mail address");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private ContactEntry constructContact() {
        return new ContactEntry(nameTextField.getText(), lastNameTextField.getText(), 
            nicknameTextField.getText(), titleTextField.getText());
    }
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
       
        ContactEntry contact = constructContact();
                
        try {
            model.processResult(contact, emailsListModel.getList());
            setVisible(false);
            dispose();
        } catch (MissingNameException e) {
            errorMessageLabel.setText("Please enter contact's name");
        } catch (NameDuplicateException e) {
            errorMessageLabel.setText("An entry with such name already exists");
        }             
    }//GEN-LAST:event_okButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.getParent().setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getParent().setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void emailTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyTyped
        emailErrorMessageLabel.setText("");
    }//GEN-LAST:event_emailTextFieldKeyTyped

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (jList1.getSelectedIndex() != -1)
             emailsListModel.remove(jList1.getSelectedIndex());
    }//GEN-LAST:event_removeButtonActionPerformed

    private void changeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCancelButtonActionPerformed
        changeAddressDialog.setVisible(false);
        this.setEnabled(true);
    }//GEN-LAST:event_changeCancelButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (jList1.getSelectedIndex() != -1) {
            changeAddressDialog.pack();
            changeAddressDialog.setVisible(true);
            this.setEnabled(false);
        }            
    }//GEN-LAST:event_editButtonActionPerformed

    private void changeConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeConfirmButtonActionPerformed
        try{      
            String newEmail = changeAddressTextField.getText();     
            emailsListModel.modify(jList1.getSelectedIndex(), new EmailEntry(newEmail, curFormat));
            changeAddressDialog.setVisible(false);
            this.setEnabled(true);
        } catch (InvalidEmailException e) {
            changeAddressErrorMessageLabel.setText("Please enter a valid email");
        }
    }//GEN-LAST:event_changeConfirmButtonActionPerformed

    private void lastNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameTextFieldKeyTyped
        errorMessageLabel.setText("");
    }//GEN-LAST:event_lastNameTextFieldKeyTyped

    private void nameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyTyped
        errorMessageLabel.setText("");
    }//GEN-LAST:event_nameTextFieldKeyTyped
   
    private void updateCurrentEmail() {
        int ind = jList1.getSelectedIndex();
        if (ind != -1) {            
            emailsListModel.get(ind).setFormat(curFormat);
            emailsListModel.modify(ind, emailsListModel.get(ind));
        }
    }
    
    private void htmlRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlRadioButtonActionPerformed
        // TODO add your handling code here:
        curFormat = Format.HTML;
        updateCurrentEmail();
    }//GEN-LAST:event_htmlRadioButtonActionPerformed

    private void plainTextRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainTextRadioButtonActionPerformed
        curFormat = Format.Plain;
        updateCurrentEmail();
    }//GEN-LAST:event_plainTextRadioButtonActionPerformed

    private void customRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customRadioButtonActionPerformed
        curFormat = Format.Custom;
        updateCurrentEmail();
    }//GEN-LAST:event_customRadioButtonActionPerformed

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        jList1.clearSelection();
    }//GEN-LAST:event_emailTextFieldFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NamePanel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JDialog changeAddressDialog;
    private javax.swing.JLabel changeAddressErrorMessageLabel;
    private javax.swing.JLabel changeAddressLabel;
    private javax.swing.JTextField changeAddressTextField;
    private javax.swing.JButton changeCancelButton;
    private javax.swing.JButton changeConfirmButton;
    private javax.swing.JRadioButton customRadioButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailErrorMessageLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.ButtonGroup formatButtonGroup;
    private javax.swing.JLabel formatLabel;
    private javax.swing.JRadioButton htmlRadioButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JTextField nicknameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton plainTextRadioButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
